### ISSUE TITLE
The R2 index is negative

### ISSUE THREAD

**Issue by fert-feet** [Meizhen2023/SARID#6]
Hi! First of all, this is a great project, but I seem to have some problems running it and would like to ask for some help.
The problem is that no matter what my epoch is set to, the `R2` index will always be negative, in the best case `R2`=-0.00127.

The following are some changes I made to the project. First, in order to adapt to the dimensions of the "model_epoch_best_R.ckpt" file, I changed the `n_mfcc` of MFCC to 128, and set the `d_model` = 128 and `nhead` = 8 of transformer, which are all the changes.

I'm running on **linux** and I don't know if this will affect me, but the same thing happened when I ran it on **windows**.

**Comment by fert-feet** [comment]
It would be very kind of you to reply to me during your busy schedule！

**Comment by Meizhen2023** [comment]
Hi, I run this code in Windows, and I think the operating system will not have a big effect on the results. Based on your question, yes you need to change some parameters of the model according to your feature, but it is weird if R2 is negative, something I could suggest is to check your features, model, labels, predictions, etc. especially the test part.

**Comment by fert-feet** [comment]
Thank you for your reply! I double-checked the code of test part and the generation of R2, and I think there should be no problem in this part. In order to verify the correctness of the dataset, I also replaced the dataset in the test part with the training data set, but the R2 index was still negative，does this indicate that there is a problem with the data set I generated?

**Comment by fert-feet** [comment]
> Hi, I run this code in Windows, and I think the operating system will not have a big effect on the results. Based on your question, yes you need to change some parameters of the model according to your feature, but it is weird if R2 is negative, something I could suggest is to check your features, model, labels, predictions, etc. especially the test part.

Thank you for your reply! I double-checked the code of test part and the generation of R2, and I think there should be no problem in this part. In order to verify the correctness of the dataset, I also replaced the dataset in the test part with the training data set, but the R2 index was still negative，does this indicate that there is a problem with the data set I generated?

**Comment by fert-feet** [comment]
Thank you for your kind reply!

**Comment by fert-feet** [comment]
> Hi, I run this code in Windows, and I think the operating system will not have a big effect on the results. Based on your question, yes you need to change some parameters of the model according to your feature, but it is weird if R2 is negative, something I could suggest is to check your features, model, labels, predictions, etc. especially the test part.

Thank you for your kind reply!
